name: Update steam stats

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    env:
      UPDATE_OPTION: GIST
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      GIST_ID: 4ddab6ce007e215174a893f896eea590
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install steam-box
        run: go install github.com/YouEclipse/steam-box/cmd/box@latest

      - name: Waka box
        run: |
          box
          git config --global user.email "bot@github.com" && git config --global user.name "Steam-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull --rebase && git push
